import 'package:flutter/material.dart';
import '../../core/domain/entities/channel.dart';
import '../../core/domain/entities/playlist.dart';
import '../../core/domain/entities/stream_source.dart';
import '../../core/video/video_library_repository.dart';
import '../player/player_screen.dart';

class VideoLibraryScreen extends StatefulWidget { const VideoLibraryScreen({super.key}); @override State<VideoLibraryScreen> createState()=>_VideoLibraryScreenState(); }
class _VideoLibraryScreenState extends State<VideoLibraryScreen>{
 final _repo=VideoLibraryRepository();final _title=TextEditingController();final _url=TextEditingController();final _category=TextEditingController(text:'Vídeos');List<VideoLibraryItem> _items=const [];
 @override void initState(){super.initState();_load();} Future<void> _load()async{final v=await _repo.load();if(mounted)setState(()=>_items=v);} @override void dispose(){_title.dispose();_url.dispose();_category.dispose();super.dispose();}
 Future<void> _add()async{final title=_title.text.trim();final uri=Uri.tryParse(_url.text.trim());if(title.isEmpty||uri==null||!{'http','https'}.contains(uri.scheme))return;await _repo.upsert(VideoLibraryItem(id:'video-'+DateTime.now().microsecondsSinceEpoch.toString(),title:title,url:uri,category:_category.text.trim().isEmpty?'Vídeos':_category.text.trim()));_title.clear();_url.clear();await _load();}
 PlaylistEntry _entry(VideoLibraryItem item)=>PlaylistEntry(id:item.id,channel:Channel(id:item.id,displayName:item.title),sources:[StreamSource(id:item.id+':source',url:item.url)]);
 @override Widget build(BuildContext context){return Scaffold(appBar:AppBar(title:const Text('Vídeos y biblioteca')),body:ListView(padding:const EdgeInsets.all(16),children:[Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(children:[const Align(alignment:Alignment.centerLeft,child:Text('Agregar vídeo o servidor',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold))),const SizedBox(height:8),const Align(alignment:Alignment.centerLeft,child:Text('Enlaces HTTP/HTTPS directos para NAS, WebDAV, Cloudflare R2/CDN u otros servidores compatibles.')),const SizedBox(height:12),TextField(controller:_title,decoration:const InputDecoration(labelText:'Título',prefixIcon:Icon(Icons.movie_outlined))),const SizedBox(height:10),TextField(controller:_url,keyboardType:TextInputType.url,decoration:const InputDecoration(labelText:'Dirección del vídeo',hintText:'https://nas.local/peliculas/pelicula.mp4',prefixIcon:Icon(Icons.link))),const SizedBox(height:10),TextField(controller:_category,decoration:const InputDecoration(labelText:'Categoría',prefixIcon:Icon(Icons.folder_outlined))),const SizedBox(height:12),FilledButton.icon(onPressed:_add,icon:const Icon(Icons.add),label:const Text('Agregar a mi biblioteca'))]))),const SizedBox(height:16),Text('Mi biblioteca ('+_items.length.toString()+')',style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:8),if(_items.isEmpty)const Card(child:ListTile(leading:Icon(Icons.video_library_outlined),title:Text('Biblioteca vacía'),subtitle:Text('Agrega películas, series o vídeos desde tu servidor.')))else..._items.map((item)=>Card(child:ListTile(leading:const Icon(Icons.movie_outlined),title:Text(item.title),subtitle:Text(item.category),onTap:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>PlayerScreen(entry:_entry(item)))),trailing:IconButton(onPressed:()=>_repo.remove(item.id).then((_)=>_load()),icon:const Icon(Icons.delete_outline)))))]);}
}
