name: reproductor_iptv
description: Cross-platform IPTV player with resilient playback, playlists, EPG and diagnostics.
publish_to: "none"
version: 0.2.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.7
  video_player: ^2.14.1
  http: ^1.6.0
  shared_preferences: ^2.5.3
  file_picker: ^13.1.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  shared_preferences_platform_interface: ^2.4.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
